#!/usr/bin/env python3
"""Generate src/registers_gen.c from the integration's register table.

`custom_components/thermiq_mqtt/heatpump/thermiq_regs.py` is the single source
of truth for what a Thermia/Danfoss pump exposes. Translating it rather than
copying it means the bridge and the Home Assistant integration cannot drift:
CI regenerates and fails if the checked-in file differs.

Usage:
    python3 standalone/codegen/gen_registers.py [--check]
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TABLE = REPO / "custom_components/thermiq_mqtt/heatpump/thermiq_regs.py"
OUTPUT = REPO / "standalone/src/registers_gen.c"
OUTPUT_H = REPO / "standalone/src/registers_gen.h"

REG_TYPES = {
    "temperature": "RT_TEMPERATURE",
    "temperature_input": "RT_TEMPERATURE_INPUT",
    "sensor": "RT_SENSOR",
    "sensor_input": "RT_SENSOR_INPUT",
    "sensor_language": "RT_SENSOR_LANGUAGE",
    "sensor_boolean": "RT_SENSOR_BOOLEAN",
    "binary_sensor": "RT_BINARY_SENSOR",
    "time": "RT_TIME",
    "time_input": "RT_TIME_INPUT",
    "select_input": "RT_SELECT_INPUT",
    "generated_input": "RT_GENERATED_INPUT",
    "generated_sensor": "RT_GENERATED_SENSOR",
    "generated_input_boolean": "RT_GENERATED_INPUT_BOOLEAN",
}

# Types whose min/max slots are real bounds. The bitmask types reuse the same
# slot for the mask, which is why this cannot be inferred from the value.
BOUNDED = {
    "temperature_input",
    "time_input",
    "sensor_input",
    "generated_input",
    "select_input",
}
BITMASKED = {"binary_sensor", "generated_input_boolean"}

# Mirrors _DEVICE_CLASS_MAP in the integration's binary_sensor.py.
DEVICE_CLASSES = {
    "compressor_on": "DC_RUNNING",
    "brine_pump_on": "DC_RUNNING",
    "supply_pump_on": "DC_RUNNING",
    "hotwaterproduction_on": "DC_RUNNING",
    "active_cooling_on": "DC_RUNNING",
    "passive_cooling_on": "DC_RUNNING",
    "boiler_3kw_on": "DC_HEAT",
    "boiler_6kw_on": "DC_HEAT",
    "aux1_heating_on": "DC_HEAT",
    "aux2_heating_on": "DC_HEAT",
    "alarm_indication_on": "DC_PROBLEM",
    "highpressure_alm": "DC_PROBLEM",
    "lowpressure_alm": "DC_PROBLEM",
    "motorbreaker_alm": "DC_PROBLEM",
    "brine_flow_alm": "DC_PROBLEM",
    "brine_temperature_alm": "DC_PROBLEM",
    "outdoor_sensor_alm": "DC_PROBLEM",
    "supplyline_sensor_alm": "DC_PROBLEM",
    "returnline_sensor_alm": "DC_PROBLEM",
    "boiler_sensor_alm": "DC_PROBLEM",
    "indoor_sensor_alm": "DC_PROBLEM",
    "phase_order_alm": "DC_PROBLEM",
    "overheating_alm": "DC_PROBLEM",
    "opt_phasemeassure_installed": "DC_CONNECTIVITY",
    "opt_2_installed": "DC_CONNECTIVITY",
    "opt_hgw_installed": "DC_CONNECTIVITY",
    "opt_4_installed": "DC_CONNECTIVITY",
    "opt_5_installed": "DC_CONNECTIVITY",
    "opt_6_installed": "DC_CONNECTIVITY",
    "opt_optimum_installed": "DC_CONNECTIVITY",
    "opt_flowguard_installed": "DC_CONNECTIVITY",
}

MODE_KEYS = ["mode0", "mode1", "mode2", "mode3", "mode4"]
LANGUAGES = ["en", "se", "fi", "no", "de"]


def load_table():
    spec = importlib.util.spec_from_file_location("thermiq_regs", TABLE)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.reg_id, module.id_names


def c_string(text: str) -> str:
    return json.dumps(text, ensure_ascii=False)


def c_double(value) -> str:
    return repr(float(value))


def generate() -> str:
    reg_id, id_names = load_table()

    unknown = {row[1] for row in reg_id.values()} - set(REG_TYPES)
    if unknown:
        raise SystemExit(
            f"unknown register types {sorted(unknown)}: add them to REG_TYPES "
            f"and to enum reg_type in src/registers.h"
        )
    missing = [mode for mode in MODE_KEYS if mode not in id_names]
    if missing:
        raise SystemExit(f"mode names missing from the table: {missing}")
    stray = set(DEVICE_CLASSES) - set(reg_id)
    if stray:
        raise SystemExit(f"device classes for unknown registers: {sorted(stray)}")

    # One value slot per distinct register. Several keys can share one - a
    # status word carries many bitmasked binary sensors.
    slots = sorted({row[0] for row in reg_id.values()})
    slot_of = {name: index for index, name in enumerate(slots)}

    lines = [
        "/* @generated by standalone/codegen/gen_registers.py - do not edit.",
        " *",
        " * Source of truth:",
        " * custom_components/thermiq_mqtt/heatpump/thermiq_regs.py",
        " *",
        " * Regenerate with:",
        " *     python3 standalone/codegen/gen_registers.py",
        " */",
        '#include "registers.h"',
        "",
        "const char *const LANGUAGE_CODES[LANGUAGE_COUNT] = {"
        + ", ".join(c_string(code) for code in LANGUAGES)
        + "};",
        "",
        "const char *const MODE_NAMES[MODE_COUNT][LANGUAGE_COUNT] = {",
    ]
    for mode in MODE_KEYS:
        lines.append("    {" + ", ".join(c_string(n) for n in id_names[mode]) + "},")
    lines += ["};", ""]

    lines.append("const struct reg_def REGISTERS[] = {")
    for key, row in reg_id.items():
        regtype = row[1]
        names = id_names.get(key)
        if names is None:
            # The integration falls back to the key for every language
            names = [key] * LANGUAGE_COUNT_PY
        elif len(names) != LANGUAGE_COUNT_PY:
            raise SystemExit(f"{key}: expected 5 translations, got {len(names)}")
        lines += [
            "    {",
            f"        .key = {c_string(key)},",
            f"        .reg = {c_string(row[0])},",
            f"        .slot = {slot_of[row[0]]},",
            f"        .type = {REG_TYPES[regtype]},",
            f"        .unit = {c_string(row[2])},",
        ]
        if regtype in BOUNDED:
            lines += [
                f"        .minimum = {c_double(row[3])},",
                f"        .maximum = {c_double(row[4])},",
                "        .has_bounds = true,",
            ]
        if regtype in BITMASKED:
            lines += [
                f"        .bitmask = {int(row[3])},",
                "        .has_bitmask = true,",
            ]
        if key in DEVICE_CLASSES:
            lines.append(f"        .device_class = {DEVICE_CLASSES[key]},")
        lines += [
            f"        .panel = {int(row[5])},",
            f"        .panel_order = {int(row[6])},",
            "        .names = {" + ", ".join(c_string(n) for n in names) + "},",
            "    },",
        ]
    lines += [
        "};",
        f"const int REGISTER_COUNT = {len(reg_id)};",
        "",
        "const char *const REG_SLOT_NAMES[] = {",
    ]
    for name in slots:
        lines.append(f"    {c_string(name)},")
    lines += [
        "};",
        f"const int REG_SLOT_COUNT = {len(slots)};",
        "",
        "/* Register indices ordered by key, for binary search. */",
        "const uint16_t REG_BY_KEY[] = {",
    ]
    keys = list(reg_id)
    order = sorted(range(len(keys)), key=lambda index: keys[index])
    for start in range(0, len(order), 12):
        lines.append(
            "    " + " ".join(f"{index}," for index in order[start : start + 12])
        )
    lines += ["};", ""]

    header = (
        "/* @generated by standalone/codegen/gen_registers.py - do not edit. */\n"
        "#ifndef THERMIQ_REGISTERS_GEN_H\n"
        "#define THERMIQ_REGISTERS_GEN_H\n"
        "\n"
        "/* Sizes the static value array; there is no dynamic allocation. */\n"
        f"#define REG_SLOT_MAX {len(slots)}\n"
        f"#define REGISTER_MAX {len(reg_id)}\n"
        "\n"
        "#endif /* THERMIQ_REGISTERS_GEN_H */\n"
    )
    return "\n".join(lines), header


LANGUAGE_COUNT_PY = 5


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify, do not write")
    args = parser.parse_args()

    generated, header = generate()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        current_h = OUTPUT_H.read_text(encoding="utf-8") if OUTPUT_H.is_file() else ""
        if current != generated or current_h != header:
            print(
                f"{OUTPUT.relative_to(REPO)} is out of date.\n"
                f"Run: python3 standalone/codegen/gen_registers.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT.relative_to(REPO)} is up to date")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    OUTPUT_H.write_text(header, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO)} and {OUTPUT_H.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
