#!/usr/bin/env python3
"""Embed web/ into the binary as src/assets_gen.c.

The container ships one file, so the UI travels inside it: no static
directory, no volume, nothing to get out of step with the binary serving it.

Usage:
    python3 standalone/codegen/gen_assets.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
WEB = REPO / "standalone/web"
OUTPUT = REPO / "standalone/src/assets_gen.c"

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
}


def c_bytes(data: bytes, width: int = 16) -> str:
    lines = []
    for start in range(0, len(data), width):
        chunk = data[start : start + width]
        lines.append("    " + " ".join(f"0x{byte:02x}," for byte in chunk))
    return "\n".join(lines)


def generate() -> str:
    files = sorted(path for path in WEB.iterdir() if path.is_file())
    if not files:
        raise SystemExit(f"no files in {WEB}")

    blobs = []
    rows = []
    for index, path in enumerate(files):
        data = path.read_bytes()
        content_type = CONTENT_TYPES.get(path.suffix)
        if not content_type:
            raise SystemExit(f"unknown content type for {path.name}")
        blobs.append(
            f"static const unsigned char asset_{index}[] = {{\n{c_bytes(data)}\n}};"
        )
        # index.html is also the root
        route = "/" if path.name == "index.html" else f"/{path.name}"
        rows.append(
            f'    {{"{route}", "{content_type}", asset_{index}, sizeof(asset_{index})}},'
        )

    return (
        "/* @generated by standalone/codegen/gen_assets.py - do not edit.\n"
        " *\n"
        " * Source: standalone/web/\n"
        " */\n"
        '#include "assets.h"\n'
        "\n" + "\n\n".join(blobs) + "\n\n"
        "const struct asset ASSETS[] = {\n" + "\n".join(rows) + "\n};\n"
        f"const int ASSET_COUNT = {len(files)};\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify, do not write")
    args = parser.parse_args()

    generated = generate()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != generated:
            print(
                f"{OUTPUT.relative_to(REPO)} is out of date.\n"
                f"Run: python3 standalone/codegen/gen_assets.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT.relative_to(REPO)} is up to date")
        return 0

    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
