#!/usr/bin/env python3
"""Render the widget parity cases through real Jinja2.

For each case in tests/widget_cases.json this writes the reference HTML that
the generated C renderer must reproduce byte for byte, plus a C file holding
the same states so the test does not need a JSON parser.

Requires Jinja2 (`pip install jinja2`). Run it whenever the template or the
cases change; CI runs it before the test.

Usage:
    python3 standalone/codegen/gen_widget_cases.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from jinja2 import Environment

REPO = Path(__file__).resolve().parents[2]
TEMPLATE = REPO / "custom_components/thermiq_mqtt/frontend/heatpump_widget.j2"
CASES = REPO / "standalone/tests/widget_cases.json"
EXPECTED_DIR = REPO / "standalone/tests/expected"
OUTPUT = REPO / "standalone/tests/widget_cases_gen.c"


def c_string(text: str) -> str:
    out = ['"']
    for byte in text.encode("utf-8"):
        char = chr(byte)
        if char == '"':
            out.append('\\"')
        elif char == "\\":
            out.append("\\\\")
        elif 0x20 <= byte < 0x7F:
            out.append(char)
        else:
            out.append(f"\\{byte:03o}")
    out.append('"')
    return "".join(out)


def render(source: str, states: dict[str, str]) -> str:
    """Render with Home Assistant's semantics for a missing entity."""

    def states_fn(entity_id):
        return states.get(entity_id, "unknown")

    def is_state_fn(entity_id, value):
        return states_fn(entity_id) == value

    env = Environment()
    env.globals.update(states=states_fn, is_state=is_state_fn)
    return env.from_string(source).render()


def main() -> int:
    source = TEMPLATE.read_text(encoding="utf-8")
    cases = json.loads(CASES.read_text(encoding="utf-8"))
    cases.pop("_comment", None)

    EXPECTED_DIR.mkdir(parents=True, exist_ok=True)
    for stale in EXPECTED_DIR.glob("*.html"):
        stale.unlink()

    rows = []
    for name, states in cases.items():
        html = render(source, states)
        (EXPECTED_DIR / f"{name}.html").write_text(html, encoding="utf-8")
        pairs = "".join(
            f"        {{{c_string(entity)}, {c_string(value)}}},\n"
            for entity, value in sorted(states.items())
        )
        rows.append(
            f"    {{\n"
            f"        {c_string(name)},\n"
            f"        (const struct case_state[]){{\n{pairs}        }},\n"
            f"        {len(states)},\n"
            f"    }},"
        )

    OUTPUT.write_text(
        "/* @generated by standalone/codegen/gen_widget_cases.py - do not edit. */\n"
        '#include "widget_cases.h"\n'
        "\n"
        "const struct widget_case WIDGET_CASES[] = {\n"
        + "\n".join(rows)
        + "\n};\n"
        f"const int WIDGET_CASE_COUNT = {len(cases)};\n",
        encoding="utf-8",
    )
    print(f"rendered {len(cases)} cases to {EXPECTED_DIR.relative_to(REPO)}")
    print(f"wrote {OUTPUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
