/* @generated by standalone/codegen/gen_registers.py - do not edit. */
#ifndef THERMIQ_REGISTERS_GEN_H
#define THERMIQ_REGISTERS_GEN_H

/* Sizes the static value array; there is no dynamic allocation. */
#define REG_SLOT_MAX 109
#define REGISTER_MAX 140

#endif /* THERMIQ_REGISTERS_GEN_H */
