/* @generated by standalone/codegen/gen_widget.py - do not edit.
 *
 * Source of truth:
 * custom_components/thermiq_mqtt/frontend/heatpump_widget.j2
 *
 * Regenerate with:
 *     python3 standalone/codegen/gen_widget.py
 */
#include <math.h>
#include <string.h>

#include "util.h"
#include "widget.h"

const struct widget_entity WIDGET_ENTITIES[] = {
    {"binary_sensor.thermiq_mqtt_vp1_alarm_indication_on", "binary_sensor", "alarm_indication_on", false},
    {"sensor.thermiq_mqtt_vp1_brine_out_t", "sensor", "brine_out_t", false},
    {"sensor.thermiq_mqtt_vp1_brine_in_t", "sensor", "brine_in_t", false},
    {"sensor.thermiq_mqtt_vp1_supplyline_t", "sensor", "supplyline_t", false},
    {"sensor.thermiq_mqtt_vp1_returnline_t", "sensor", "returnline_t", false},
    {"sensor.thermiq_mqtt_vp1_boiler_t", "sensor", "boiler_t", false},
    {"sensor.thermiq_mqtt_vp1_pressurepipe_t", "sensor", "pressurepipe_t", false},
    {"number.thermiq_mqtt_vp1_integral2_curve_target", "number", "integral2_curve_target", false},
    {"input_boolean.hpviz_demo", "input_boolean", NULL, true},
    {"binary_sensor.thermiq_mqtt_vp1_hotwaterproduction_on", "binary_sensor", "hotwaterproduction_on", false},
    {"binary_sensor.thermiq_mqtt_vp1_supply_pump_on", "binary_sensor", "supply_pump_on", false},
    {"sensor.thermiq_mqtt_vp1_outdoor_t", "sensor", "outdoor_t", false},
    {"sensor.thermiq_mqtt_vp1_heating_stop_t", "sensor", "heating_stop_t", false},
    {"binary_sensor.pool_heating_active", "binary_sensor", NULL, false},
    {"binary_sensor.thermiq_mqtt_vp1_brine_pump_on", "binary_sensor", "brine_pump_on", false},
    {"binary_sensor.thermiq_mqtt_vp1_compressor_on", "binary_sensor", "compressor_on", false},
    {"sensor.thermiq_mqtt_vp1_supply_shunt_t", "sensor", "supply_shunt_t", false},
    {"sensor.thermiq_mqtt_vp1_time_str", "sensor", "time_str", false},
    {"binary_sensor.thermiq_mqtt_vp1_opt_hgw_installed", "binary_sensor", "opt_hgw_installed", false},
    {"sensor.thermiq_mqtt_vp1_hgw_water_t", "sensor", "hgw_water_t", false},
    {"binary_sensor.thermiq_mqtt_vp1_opt_optimum_installed", "binary_sensor", "opt_optimum_installed", false},
    {"sensor.thermiq_mqtt_vp1_supply_pump_speed", "sensor", "supply_pump_speed", false},
    {"sensor.thermiq_mqtt_vp1_brine_pump_speed", "sensor", "brine_pump_speed", false},
    {"binary_sensor.thermiq_mqtt_vp1_boiler_3kw_on", "binary_sensor", "boiler_3kw_on", false},
    {"binary_sensor.thermiq_mqtt_vp1_boiler_6kw_on", "binary_sensor", "boiler_6kw_on", false},
    {"sensor.thermiq_mqtt_vp1_communication_status", "sensor", "communication_status", false},
    {"switch.thermiq_mqtt_vp1_heatpump_evu_block", "switch", "heatpump_evu_block", false},
    {"sensor.thermiq_mqtt_vp1_indoor_t", "sensor", "indoor_t", false},
};
const int WIDGET_ENTITY_COUNT = 28;

static void m_tcol(struct buf *out, const char *const *state, jval v_t)
{
    (void)state;
    (void)v_t;
    double v_tc = median3((double)(5), jv_float(v_t, (double)(0)), (double)(50));
    (void)v_tc;
    buf_add(out, "hsl(", 4);
    buf_double(out, rint(((double)(220) * pow(((double)(1) - ((v_tc - (double)(5)) / (double)(45))), 1.5))));
    buf_add(out, ",90%,", 5);
    buf_int(out, ((v_tc <= (double)(5)) ? 66 : 52));
    buf_add(out, "%)", 2);
}

static void m_gcol(struct buf *out, const char *const *state, jval v_t)
{
    (void)state;
    (void)v_t;
    double v_tc = median3((double)((-10)), jv_float(v_t, (double)(0)), (double)(80));
    (void)v_tc;
    buf_add(out, "hsl(", 4);
    buf_double(out, rint(((double)(268) + (((v_tc + (double)(10)) / (double)(90)) * (double)(55)))));
    buf_add(out, ",72%,", 5);
    buf_double(out, rint(((double)(66) - (((v_tc + (double)(10)) / (double)(90)) * (double)(18)))));
    buf_add(out, "%)", 2);
}

static void m_bcol(struct buf *out, const char *const *state, jval v_t)
{
    (void)state;
    (void)v_t;
    double v_tc = median3((double)((-4)), jv_float(v_t, (double)(0)), (double)(2));
    (void)v_tc;
    buf_add(out, "hsl(", 4);
    buf_double(out, rint(((double)(220) - (((v_tc + (double)(4)) / (double)(6)) * (double)(28)))));
    buf_add(out, ",85%,", 5);
    buf_double(out, rint(((double)(46) + (((v_tc + (double)(4)) / (double)(6)) * (double)(22)))));
    buf_add(out, "%)", 2);
}

static void m_pcol(struct buf *out, const char *const *state, jval v_t)
{
    (void)state;
    (void)v_t;
    double v_tc = median3((double)(5), jv_float(v_t, (double)(0)), (double)(50));
    (void)v_tc;
    buf_add(out, "hsl(", 4);
    buf_double(out, rint(((double)(220) * pow(((double)(1) - ((v_tc - (double)(5)) / (double)(45))), 1.5))));
    buf_add(out, ",85%,", 5);
    buf_int(out, ((v_tc <= (double)(5)) ? 66 : 50));
    buf_add(out, "%)", 2);
}

void widget_render(struct buf *out, const char *const *state)
{
    (void)state;
    buf_add(out,
        "<style>  .hpwidget-val {width:35px;height:16px;background:#a0a0a0;text-align: center;color:white;bor"
        "der-radius: 0.25em;} .hpwidget-vald {width:45px;height:16px;background:#ffffff;text-align: center;co"
        "lor:black;border-radius: 0.25em;} .hpwidget-name-span{}.hpwidget-unit-span,.hpwidget-unit-spand{text"
        "-align:right;overflow:hidden;color:var(--primary-text-color,#222);font-size:70%} @media (prefers-col"
        "or-scheme: dark) { .hpwidget-vald {width:45px;height:16px;background:none;text-align: center;color:w"
        "hite;border-radius: 0.25em;}   .hpwidget-val {width:35px;height:16px;background:#a0a0a0;text-align: "
        "center;color:black;border-radius: 0.25em;} }    @keyframes blink { to {visibility: hidden;}} </style"
        ">\012<div style=\"height:330px;width:100%;"
        , 738);
    if ((strcmp(state[0], "on") == 0)) {
        buf_add(out, "background-color:red;", 21);
    }
    buf_add(out, "\"> <div style=\"position:absolute;left:15px;\">      ", 51);
    const char * v_t_brine = state[1];
    (void)v_t_brine;
    const char * v_t_brinein = state[2];
    (void)v_t_brinein;
    const char * v_t_sup = state[3];
    (void)v_t_sup;
    const char * v_t_ret = state[4];
    (void)v_t_ret;
    const char * v_t_boiler = state[5];
    (void)v_t_boiler;
    const char * v_t_press = state[6];
    (void)v_t_press;
    const char * v_t_pool = state[7];
    (void)v_t_pool;
    bool v_demo = (strcmp(state[8], "on") == 0);
    (void)v_demo;
    jval v_t_chg = (v_demo ? jv_i(63) : jv_s(v_t_sup));
    (void)v_t_chg;
    bool v_dhw_on = (v_demo || (strcmp(state[9], "on") == 0));
    (void)v_dhw_on;
    bool v_rad_on = (((strcmp(state[10], "on") == 0) && (!v_dhw_on)) && (str_float(state[11], (double)(99)) < str_float(state[12], (double)(0))));
    (void)v_rad_on;
    buf_add(out,
        "<div style=\"position:absolute;top:0px;left:0px;z-index:2;pointer-events:none;\"><style>@keyframes vpd"
        "W{to{stroke-dashoffset:-52px}}@keyframes vpimp{from{transform:translate(13px,13px) rotate(0deg)}to{t"
        "ransform:translate(13px,13px) rotate(360deg)}}@keyframes vpdE1{to{stroke-dashoffset:-36.0px}}@keyfra"
        "mes vpdE2{to{stroke-dashoffset:-41.4px}}@keyframes vpd0{to{stroke-dashoffset:-98.6px}}@keyframes vpd"
        "1{to{stroke-dashoffset:-91.8px}}@keyframes vpd2{to{stroke-dashoffset:-148.4px}}@keyframes vpd4{to{st"
        "roke-dashoffset:-54.0px}}@keyframes vpd7{to{stroke-dashoffset:-45.0px}}@keyframes vpd8{to{stroke-das"
        "hoffset:-99.0px}}@keyframes vpd9{to{stroke-dashoffset:-134.0px}}@keyframes vpd10{to{stroke-dashoffse"
        "t:-183.5px}}@keyframes vpd11{to{stroke-dashoffset:-38.0px}}@keyframes vpd12{to{stroke-dashoffset:-38"
        ".0px}}@keyframes vpoffs{from{offset-distance:0%}to{offset-distance:100%}}</style><svg style=\"height:"
        "300px;overflow:visible;\" viewBox=\"0 0 400 368\"><defs><linearGradient id=\"vgcab\" x1=\"0\" y1=\"0\" x2=\"1\""
        " y2=\"0\"><stop offset=\"0\" stop-color=\"#eceeef\"/><stop offset=\"0.5\" stop-color=\"#f6f7f8\"/><stop offset"
        "=\"1\" stop-color=\"#dfe1e3\"/></linearGradient></defs><rect x=\"50\" y=\"8\" width=\"125\" height=\"302\" rx=\"1"
        "0\" fill=\"url(#vgcab)\" stroke=\"#aab4ba\" stroke-width=\"2\"/><line x1=\"50\" y1=\"28\" x2=\"175\" y2=\"28\" stro"
        "ke=\"#c5cdd2\" stroke-width=\"1.5\"/><rect x=\"60\" y=\"312\" width=\"20\" height=\"5\" rx=\"2\" fill=\"#b8bfc4\"/><"
        "rect x=\"145\" y=\"312\" width=\"20\" height=\"5\" rx=\"2\" fill=\"#b8bfc4\"/><defs></defs><g id=\"piperedo\"><def"
        "s><linearGradient id=\"vgl\" gradientUnits=\"userSpaceOnUse\" x1=\"0\" y1=\"292\" x2=\"0\" y2=\"146\"><stop offs"
        "et=\"0\" stop-color=\""
        , 1619);
    m_gcol(out, state, jv_s(v_t_brinein));
    buf_add(out, "\"/><stop offset=\"1\" stop-color=\"", 32);
    m_gcol(out, state, jv_s(v_t_brinein));
    buf_add(out,
        "\"/></linearGradient><linearGradient id=\"vgt\" gradientUnits=\"userSpaceOnUse\" x1=\"81\" y1=\"0\" x2=\"147\" "
        "y2=\"0\"><stop offset=\"0\" stop-color=\""
        , 136);
    m_gcol(out, state, jv_s(v_t_brinein));
    buf_add(out, "\"/><stop offset=\"0.40\" stop-color=\"", 35);
    m_gcol(out, state, jv_s(v_t_brinein));
    buf_add(out, "\"/><stop offset=\"0.52\" stop-color=\"", 35);
    m_gcol(out, state, jv_s(v_t_press));
    buf_add(out, "\"/><stop offset=\"1\" stop-color=\"", 32);
    m_gcol(out, state, jv_s(v_t_press));
    buf_add(out,
        "\"/></linearGradient><linearGradient id=\"vgb\" gradientUnits=\"userSpaceOnUse\" x1=\"81\" y1=\"0\" x2=\"147\" "
        "y2=\"0\"><stop offset=\"0\" stop-color=\""
        , 136);
    m_gcol(out, state, jv_s(v_t_brine));
    buf_add(out, "\"/><stop offset=\"0.30\" stop-color=\"", 35);
    m_gcol(out, state, jv_s(v_t_brine));
    buf_add(out, "\"/><stop offset=\"0.66\" stop-color=\"", 35);
    m_gcol(out, state, jv_s(v_t_ret));
    buf_add(out, "\"/><stop offset=\"1\" stop-color=\"", 32);
    m_gcol(out, state, jv_s(v_t_ret));
    buf_add(out, "\"/></linearGradient></defs><path d=\"M176 294.5 H215\" fill=\"none\" stroke=\"", 73);
    m_tcol(out, state, jv_s(v_t_ret));
    buf_add(out,
        "\" stroke-width=\"8\"/><path d=\"M81.5 196 V146\" fill=\"none\" stroke=\"url(#vgl)\" stroke-width=\"8\"/><path "
        "d=\"M81.5 152 Q81.5 138.5 95 138.5 H128 Q141 138.5 141 152 V194\" fill=\"none\" stroke=\"url(#vgt)\" strok"
        "e-width=\"8\"/><path d=\"M141 250 V272 Q141 280 133 280 H90 Q81.5 280 81.5 272 V250\" fill=\"none\" stroke"
        "=\"url(#vgb)\" stroke-width=\"8\"/><path d=\"M153.5 196 V122\" fill=\"none\" stroke=\""
        , 377);
    m_tcol(out, state, jv_s(v_t_sup));
    buf_add(out, "\" stroke-width=\"8\"/><path d=\"M165 118 H217\" fill=\"none\" stroke=\"", 64);
    m_tcol(out, state, jv_s(v_t_sup));
    buf_add(out, "\" stroke-width=\"8\"/><g id=\"valve3w\">", 36);
    if (((v_dhw_on || ((!v_demo) && (strcmp(state[13], "on") == 0))) || v_rad_on)) {
        buf_add(out,
            "<path d=\"M153.5 192 V140\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" str"
            "oke-dasharray=\"18.0 34.0\" style=\"animation:vpdW 2.4s linear infinite\"/><path d=\"M-1.6 -3.4 L2.6 0 L-"
            "1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"rou"
            "nd\" style=\"offset-path:path('M153.5 192 V140');offset-rotate:auto;animation:vpoffs 2.4s linear infin"
            "ite;animation-delay:-0.83s\"/>"
            , 429);
    }
    if (v_dhw_on) {
        buf_add(out, "<path d=\"M147 118 H121 Q113 118 113 110 V88\" fill=\"none\" stroke=\"", 65);
        m_tcol(out, state, v_t_chg);
        buf_add(out,
            "\" stroke-width=\"8\" stroke-linejoin=\"round\"/><line x1=\"171\" y1=\"110\" x2=\"171\" y2=\"126\" stroke=\"rgb(60"
            ",60,60)\" stroke-width=\"2.5\"/>"
            , 129);
    } else {
        buf_add(out,
            "<path d=\"M147 118 H121 Q113 118 113 110 V88\" fill=\"none\" stroke=\"#b0bec5\" stroke-width=\"8\" stroke-li"
            "nejoin=\"round\"/><line x1=\"137\" y1=\"110.5\" x2=\"137\" y2=\"125.5\" stroke=\"rgb(60,60,60)\" stroke-width=\"2"
            ".5\"/>"
            , 205);
    }
    buf_add(out,
        "<path d=\"M147 131.5 L153.5 118 L160 131.5 Z\" fill=\"#ffffff\" stroke=\"rgb(60,60,60)\" stroke-width=\"1.9"
        "\" stroke-linejoin=\"round\"/><path d=\"M140.5 111.5 L153.5 118 L140.5 124.5 Z\" fill=\"#ffffff\" stroke=\"r"
        "gb(60,60,60)\" stroke-width=\"1.9\" stroke-linejoin=\"round\"/><path d=\"M166.5 111.5 L153.5 118 L166.5 12"
        "4.5 Z\" fill=\"#ffffff\" stroke=\"rgb(60,60,60)\" stroke-width=\"1.9\" stroke-linejoin=\"round\"/></g><path d"
        "=\"M153.5 248 V287 Q153.5 294.5 162 294.5 H176\" fill=\"none\" stroke=\""
        , 467);
    m_tcol(out, state, jv_s(v_t_ret));
    buf_add(out,
        "\" stroke-width=\"8\"/><path d=\"M26.5 154 V146 Q26.5 138.5 34 138.5 H59 Q66.5 138.5 66.5 146 V196\" fill"
        "=\"none\" stroke=\""
        , 116);
    m_bcol(out, state, jv_s(v_t_brinein));
    buf_add(out,
        "\" stroke-width=\"8\" stroke-linejoin=\"round\"/><path d=\"M66.5 246 V287 Q66.5 294.5 59 294.5 H10\" fill=\""
        "none\" stroke=\""
        , 114);
    m_bcol(out, state, jv_s(v_t_brine));
    buf_add(out,
        "\" stroke-width=\"8\" stroke-linejoin=\"round\"/><g id=\"vvx-inner\"><rect x=\"130\" y=\"194\" width=\"34\" heigh"
        "t=\"54\" rx=\"3\" fill=\"#ffffff\" stroke=\"#78909c\" stroke-width=\"2.2\"/><line x1=\"130\" y1=\"248\" x2=\"164\" y"
        "2=\"194\" stroke=\"#78909c\" stroke-width=\"1.6\"/><circle cx=\"141\" cy=\"194\" r=\"2.4\" fill=\"#78909c\"/><circ"
        "le cx=\"141\" cy=\"248\" r=\"2.4\" fill=\"#78909c\"/><circle cx=\"153.5\" cy=\"194\" r=\"2.4\" fill=\"#78909c\"/><ci"
        "rcle cx=\"153.5\" cy=\"248\" r=\"2.4\" fill=\"#78909c\"/></g><g id=\"vvx-evap\"><rect x=\"59\" y=\"194\" width=\"27"
        "\" height=\"54\" rx=\"3\" fill=\"#ffffff\" stroke=\"#78909c\" stroke-width=\"2.2\"/><line x1=\"59\" y1=\"248\" x2=\""
        "86\" y2=\"194\" stroke=\"#78909c\" stroke-width=\"1.6\"/><circle cx=\"66.5\" cy=\"194\" r=\"2.4\" fill=\"#78909c\"/"
        "><circle cx=\"66.5\" cy=\"248\" r=\"2.4\" fill=\"#78909c\"/><circle cx=\"81.5\" cy=\"194\" r=\"2.4\" fill=\"#78909c"
        "\"/><circle cx=\"81.5\" cy=\"248\" r=\"2.4\" fill=\"#78909c\"/></g><path d=\"M100 272 L114 280 L100 288 Z\" fil"
        "l=\"#ffffff\" stroke=\"rgb(60,60,60)\" stroke-width=\"1.9\"/><path d=\"M128 272 L114 280 L128 288 Z\" fill=\""
        "#ffffff\" stroke=\"rgb(60,60,60)\" stroke-width=\"1.9\"/><line x1=\"100\" y1=\"271\" x2=\"100\" y2=\"289\" stroke"
        "=\"rgb(60,60,60)\" stroke-width=\"3\"/></g><style>.vptankglow{animation:vptankp 2s ease-in-out infinite;"
        "}@keyframes vptankp{50%{opacity:0.55;}}</style><path class=\""
        , 1260);
    buf_str(out, (v_dhw_on ? "vptankglow" : ""));
    buf_add(out, "\" d=\"M90 41 Q90 24 113.5 24 Q137 24 137 41 V67 Q137 84 113.5 84 Q90 84 90 67 Z\" fill=\"", 86);
    m_tcol(out, state, jv_s(v_t_boiler));
    buf_add(out, "\" fill-opacity=\"", 16);
    buf_double(out, (v_dhw_on ? 1.0 : 0.85));
    buf_add(out,
        "\" stroke=\"#78909c\" stroke-width=\"2\"/><path d=\"M96 38 Q96 30 104 28\" fill=\"none\" stroke=\"#ffffff\" str"
        "oke-width=\"2\" stroke-linecap=\"round\" opacity=\"0.5\"/><text x=\"113.5\" y=\"48\" text-anchor=\"middle\" font"
        "-size=\"11\" fill=\"#ffffff\" opacity=\"0.9\">VV-tank</text><text x=\"113.5\" y=\"68\" text-anchor=\"middle\" fo"
        "nt-size=\"15\" font-weight=\"bold\" fill=\"#ffffff\">"
        , 347);
    buf_str(out, state[5]);
    buf_add(out, "&#176;</text>", 13);
    if ((v_demo || (strcmp(state[14], "on") == 0))) {
        buf_add(out,
            "<path d=\"M26.5 152 V146 Q26.5 138.5 34 138.5 H59 Q66.5 138.5 66.5 146 V190\" fill=\"none\" stroke=\"#fff"
            "fff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-dasharray=\"18.1 14.8\" style=\"animation:vpd0 3."
            "6s linear infinite\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width"
            "=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M26.5 152 V146 Q26.5 "
            "138.5 34 138.5 H59 Q66.5 138.5 66.5 146 V190');offset-rotate:auto;animation:vpoffs 3.6s linear infin"
            "ite;animation-delay:-0.66s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stro"
            "ke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M26.5 152 V14"
            "6 Q26.5 138.5 34 138.5 H59 Q66.5 138.5 66.5 146 V190');offset-rotate:auto;animation:vpoffs 3.6s line"
            "ar infinite;animation-delay:-1.86s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffff"
            "ff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M26.5"
            " 152 V146 Q26.5 138.5 34 138.5 H59 Q66.5 138.5 66.5 146 V190');offset-rotate:auto;animation:vpoffs 3"
            ".6s linear infinite;animation-delay:-3.06s\"/><path d=\"M66.5 252 V287 Q66.5 294.5 59 294.5 H14\" fill="
            "\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-dasharray=\"16.8 13.8\" style"
            "=\"animation:vpd1 3.4s linear infinite\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#f"
            "fffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M6"
            "6.5 252 V287 Q66.5 294.5 59 294.5 H14');offset-rotate:auto;animation:vpoffs 3.4s linear infinite;ani"
            "mation-delay:-0.62s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-widt"
            "h=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M66.5 252 V287 Q66.5"
            " 294.5 59 294.5 H14');offset-rotate:auto;animation:vpoffs 3.4s linear infinite;animation-delay:-1.76"
            "s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-lin"
            "ecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M66.5 252 V287 Q66.5 294.5 59 294.5 H1"
            "4');offset-rotate:auto;animation:vpoffs 3.4s linear infinite;animation-delay:-2.89s\"/>"
            , 2186);
    }
    if ((v_demo || (strcmp(state[15], "on") == 0))) {
        buf_add(out,
            "<path d=\"M81.5 190 V152 Q81.5 138.5 95 138.5 H128 Q141 138.5 141 152 V186\" fill=\"none\" stroke=\"#ffff"
            "ff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-dasharray=\"13.6 11.1\" style=\"animation:vpd2 5.5"
            "s linear infinite\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width="
            "\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M81.5 190 V152 Q81.5 1"
            "38.5 95 138.5 H128 Q141 138.5 141 152 V186');offset-rotate:auto;animation:vpoffs 5.5s linear infinit"
            "e;animation-delay:-0.50s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke"
            "-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M81.5 190 V152 "
            "Q81.5 138.5 95 138.5 H128 Q141 138.5 141 152 V186');offset-rotate:auto;animation:vpoffs 5.5s linear "
            "infinite;animation-delay:-1.42s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\""
            " stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M81.5 19"
            "0 V152 Q81.5 138.5 95 138.5 H128 Q141 138.5 141 152 V186');offset-rotate:auto;animation:vpoffs 5.5s "
            "linear infinite;animation-delay:-2.34s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#"
            "ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M"
            "81.5 190 V152 Q81.5 138.5 95 138.5 H128 Q141 138.5 141 152 V186');offset-rotate:auto;animation:vpoff"
            "s 5.5s linear infinite;animation-delay:-3.25s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" st"
            "roke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:"
            "path('M81.5 190 V152 Q81.5 138.5 95 138.5 H128 Q141 138.5 141 152 V186');offset-rotate:auto;animatio"
            "n:vpoffs 5.5s linear infinite;animation-delay:-4.17s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"n"
            "one\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offse"
            "t-path:path('M81.5 190 V152 Q81.5 138.5 95 138.5 H128 Q141 138.5 141 152 V186');offset-rotate:auto;a"
            "nimation:vpoffs 5.5s linear infinite;animation-delay:-5.09s\"/><path d=\"M141 254 V272 Q141 280 133 28"
            "0 H128\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-dasharray=\"9.9"
            " 8.1\" style=\"animation:vpdE1 1.4s linear infinite\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none"
            "\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-p"
            "ath:path('M141 254 V272 Q141 280 133 280 H128');offset-rotate:auto;animation:vpoffs 1.4s linear infi"
            "nite;animation-delay:-0.39s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" str"
            "oke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M141 254 V27"
            "2 Q141 280 133 280 H128');offset-rotate:auto;animation:vpoffs 1.4s linear infinite;animation-delay:-"
            "1.08s\"/><path d=\"M98 280 H90 Q81.5 280 81.5 272 V252\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6"
            "\" stroke-linecap=\"round\" stroke-dasharray=\"11.4 9.3\" style=\"animation:vpdE2 1.5s linear infinite\"/><"
            "path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap="
            "\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M98 280 H90 Q81.5 280 81.5 272 V252');offse"
            "t-rotate:auto;animation:vpoffs 1.5s linear infinite;animation-delay:-0.41s\"/><path d=\"M-1.6 -3.4 L2."
            "6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoi"
            "n=\"round\" style=\"offset-path:path('M98 280 H90 Q81.5 280 81.5 272 V252');offset-rotate:auto;animatio"
            "n:vpoffs 1.5s linear infinite;animation-delay:-1.16s\"/>"
            , 3555);
    }
    if (v_dhw_on) {
        buf_add(out,
            "<path d=\"M144 118 H121 Q113 118 113 110 V92\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-"
            "linecap=\"round\" stroke-dasharray=\"9.9 8.1\" style=\"animation:vpd4 3.0s linear infinite\"/><path d=\"M-1"
            ".6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" str"
            "oke-linejoin=\"round\" style=\"offset-path:path('M144 118 H121 Q113 118 113 110 V92');offset-rotate:aut"
            "o;animation:vpoffs 3.0s linear infinite;animation-delay:-0.55s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3."
            "4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" st"
            "yle=\"offset-path:path('M144 118 H121 Q113 118 113 110 V92');offset-rotate:auto;animation:vpoffs 3.0s"
            " linear infinite;animation-delay:-1.55s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\""
            "#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('"
            "M144 118 H121 Q113 118 113 110 V92');offset-rotate:auto;animation:vpoffs 3.0s linear infinite;animat"
            "ion-delay:-2.55s\"/>"
            , 1019);
    }
    if (v_rad_on) {
        buf_add(out,
            "<path d=\"M170 118 H215\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" strok"
            "e-dasharray=\"12.4 10.1\" style=\"animation:vpd7 2.4s linear infinite\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1."
            "6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round"
            "\" style=\"offset-path:path('M170 118 H215');offset-rotate:auto;animation:vpoffs 2.4s linear infinite;"
            "animation-delay:-0.66s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-w"
            "idth=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M170 118 H215');o"
            "ffset-rotate:auto;animation:vpoffs 2.4s linear infinite;animation-delay:-1.86s\"/><path d=\"M215 294.5"
            " H162 Q153.5 294.5 153.5 287 V254\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"r"
            "ound\" stroke-dasharray=\"20.0 29.5\" style=\"animation:vpd8 2.6s linear infinite\"/><path d=\"M-1.6 -3.4 "
            "L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-line"
            "join=\"round\" style=\"offset-path:path('M215 294.5 H162 Q153.5 294.5 153.5 287 V254');offset-rotate:au"
            "to;animation:vpoffs 2.6s linear infinite;animation-delay:-0.53s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3"
            ".4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" s"
            "tyle=\"offset-path:path('M215 294.5 H162 Q153.5 294.5 153.5 287 V254');offset-rotate:auto;animation:v"
            "poffs 2.6s linear infinite;animation-delay:-1.83s\"/>"
            , 1452);
    }
    if (((!v_demo) && (strcmp(state[13], "on") == 0))) {
        buf_add(out, "<style>.vppoolwave{fill:none;stroke:", 36);
        m_pcol(out, state, jv_s(v_t_pool));
        buf_add(out,
            ";stroke-width:2.4;stroke-linecap:round;animation:vppoolw 1.6s ease-in-out infinite;}@keyframes vppoo"
            "lw{50%{transform:translateX(5px);}}</style><path d=\"M214 294.5 H217 Q224.5 294.5 224.5 287 V277.5 Q2"
            "24.5 270 232 270\" fill=\"none\" stroke=\""
            , 238);
        m_tcol(out, state, jv_s(v_t_ret));
        buf_add(out,
            "\" stroke-width=\"8\" stroke-linecap=\"butt\" stroke-linejoin=\"round\"/><path d=\"M212 118 H217 Q224.5 118 "
            "224.5 125.5 V238.5 Q224.5 246 232 246\" fill=\"none\" stroke=\""
            , 159);
        m_tcol(out, state, jv_s(v_t_sup));
        buf_add(out,
            "\" stroke-width=\"8\" stroke-linecap=\"butt\" stroke-linejoin=\"round\"/><path d=\"M258 246 H300\" fill=\"none"
            "\" stroke=\""
            , 110);
        m_pcol(out, state, jv_s(v_t_pool));
        buf_add(out, "\" stroke-width=\"8\" stroke-linecap=\"butt\"/><path d=\"M258 270 H300\" fill=\"none\" stroke=\"", 86);
        m_tcol(out, state, jv_s(v_t_ret));
        buf_add(out,
            "\" stroke-width=\"8\" stroke-linecap=\"butt\"/><rect x=\"232\" y=\"234\" width=\"26\" height=\"48\" rx=\"3\" fill=\""
            "var(--card-background-color,#ffffff)\" stroke=\"#78909c\" stroke-width=\"2\"/><line x1=\"232\" y1=\"282\" x2="
            "\"258\" y2=\"234\" stroke=\"#78909c\" stroke-width=\"1.6\"/><circle cx=\"232\" cy=\"246\" r=\"2.6\" fill=\"#78909c\""
            "/><circle cx=\"232\" cy=\"270\" r=\"2.6\" fill=\"#78909c\"/><circle cx=\"258\" cy=\"246\" r=\"2.6\" fill=\"#78909c\""
            "/><circle cx=\"258\" cy=\"270\" r=\"2.6\" fill=\"#78909c\"/><text x=\"245\" y=\"294\" text-anchor=\"middle\" font-"
            "size=\"7.5\" fill=\"#78909c\">VVX</text><path d=\"M231 270 Q224.5 270 224.5 277.5 V287 Q224.5 294.5 217 2"
            "94.5 H162 Q153.5 294.5 153.5 287 V254\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-lineca"
            "p=\"round\" stroke-dasharray=\"14.7 12.1\" style=\"animation:vpd9 5.2s linear infinite\"/><path d=\"M-1.6 -"
            "3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-"
            "linejoin=\"round\" style=\"offset-path:path('M231 270 Q224.5 270 224.5 277.5 V287 Q224.5 294.5 217 294."
            "5 H162 Q153.5 294.5 153.5 287 V254');offset-rotate:auto;animation:vpoffs 5.2s linear infinite;animat"
            "ion-delay:-0.57s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\""
            "2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M231 270 Q224.5 270 224"
            ".5 277.5 V287 Q224.5 294.5 217 294.5 H162 Q153.5 294.5 153.5 287 V254');offset-rotate:auto;animation"
            ":vpoffs 5.2s linear infinite;animation-delay:-1.61s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"no"
            "ne\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset"
            "-path:path('M231 270 Q224.5 270 224.5 277.5 V287 Q224.5 294.5 217 294.5 H162 Q153.5 294.5 153.5 287 "
            "V254');offset-rotate:auto;animation:vpoffs 5.2s linear infinite;animation-delay:-2.65s\"/><path d=\"M-"
            "1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" st"
            "roke-linejoin=\"round\" style=\"offset-path:path('M231 270 Q224.5 270 224.5 277.5 V287 Q224.5 294.5 217"
            " 294.5 H162 Q153.5 294.5 153.5 287 V254');offset-rotate:auto;animation:vpoffs 5.2s linear infinite;a"
            "nimation-delay:-3.69s\"/><path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-wi"
            "dth=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M231 270 Q224.5 27"
            "0 224.5 277.5 V287 Q224.5 294.5 217 294.5 H162 Q153.5 294.5 153.5 287 V254');offset-rotate:auto;anim"
            "ation:vpoffs 5.2s linear infinite;animation-delay:-4.73s\"/><path d=\"M170 118 H217 Q224.5 118 224.5 1"
            "25.5 V238.5 Q224.5 246 231 246\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"roun"
            "d\" stroke-dasharray=\"20.0 16.7\" style=\"animation:vpd10 5.2s linear infinite\"/><path d=\"M-1.6 -3.4 L2"
            ".6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejo"
            "in=\"round\" style=\"offset-path:path('M170 118 H217 Q224.5 118 224.5 125.5 V238.5 Q224.5 246 231 246')"
            ";offset-rotate:auto;animation:vpoffs 5.2s linear infinite;animation-delay:-0.57s\"/><path d=\"M-1.6 -3"
            ".4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-l"
            "inejoin=\"round\" style=\"offset-path:path('M170 118 H217 Q224.5 118 224.5 125.5 V238.5 Q224.5 246 231 "
            "246');offset-rotate:auto;animation:vpoffs 5.2s linear infinite;animation-delay:-1.61s\"/><path d=\"M-1"
            ".6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" str"
            "oke-linejoin=\"round\" style=\"offset-path:path('M170 118 H217 Q224.5 118 224.5 125.5 V238.5 Q224.5 246"
            " 231 246');offset-rotate:auto;animation:vpoffs 5.2s linear infinite;animation-delay:-2.65s\"/><path d"
            "=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round"
            "\" stroke-linejoin=\"round\" style=\"offset-path:path('M170 118 H217 Q224.5 118 224.5 125.5 V238.5 Q224."
            "5 246 231 246');offset-rotate:auto;animation:vpoffs 5.2s linear infinite;animation-delay:-3.69s\"/><p"
            "ath d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\""
            "round\" stroke-linejoin=\"round\" style=\"offset-path:path('M170 118 H217 Q224.5 118 224.5 125.5 V238.5 "
            "Q224.5 246 231 246');offset-rotate:auto;animation:vpoffs 5.2s linear infinite;animation-delay:-4.73s"
            "\"/><path d=\"M298 246 H260\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" st"
            "roke-dasharray=\"20.0 18.0\" style=\"animation:vpd11 1.4s linear infinite\"/><path d=\"M-1.6 -3.4 L2.6 0 "
            "L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"r"
            "ound\" style=\"offset-path:path('M298 246 H260');offset-rotate:auto;animation:vpoffs 1.4s linear infin"
            "ite;animation-delay:-0.74s\"/><path d=\"M260 270 H298\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\""
            " stroke-linecap=\"round\" stroke-dasharray=\"20.0 18.0\" style=\"animation:vpd12 1.4s linear infinite\"/><"
            "path d=\"M-1.6 -3.4 L2.6 0 L-1.6 3.4\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap="
            "\"round\" stroke-linejoin=\"round\" style=\"offset-path:path('M260 270 H298');offset-rotate:auto;animatio"
            "n:vpoffs 1.4s linear infinite;animation-delay:-0.74s\"/><rect x=\"300\" y=\"233\" width=\"78\" height=\"48\" "
            "rx=\"9\" fill=\""
            , 5113);
        m_pcol(out, state, jv_s(v_t_pool));
        buf_add(out, "\" fill-opacity=\"0.14\" stroke=\"", 30);
        m_pcol(out, state, jv_s(v_t_pool));
        buf_add(out,
            "\" stroke-width=\"2\"/><g class=\"vppoolwave\"><path d=\"M308 250 q6,-6 12,0 t12,0 t12,0 t12,0 t12,0\"/><pa"
            "th d=\"M308 264 q6,-6 12,0 t12,0 t12,0 t12,0 t12,0\"/></g><text x=\"339\" y=\"228\" text-anchor=\"middle\" f"
            "ont-size=\"10\" fill=\"#90a4ae\">"
            , 229);
        buf_str(out, state[16]);
        buf_add(out, "&#176; &#8594; ", 15);
        buf_str(out, state[7]);
        buf_add(out, "&#176;</text><text x=\"339\" y=\"297\" text-anchor=\"middle\" font-size=\"10\" font-weight=\"bold\" fill=\"", 96);
        m_pcol(out, state, jv_s(v_t_pool));
        buf_add(out, "\">POOL</text>", 13);
    }
    buf_add(out,
        "</svg></div> <div class=\"hpwidget-val\" title=\"Time\" style=\"position:absolute;top:303px;left:20px;wid"
        "th:150px;z-index:3;\">   <span class=\"hpwidget-name-span\" id=\"hpwidget-timestamp_d\">"
        , 183);
    buf_str(out, state[17]);
    buf_add(out,
        "</span><span class=\"hpwidget-unit-span\"></span></span></div> <div class=\"hpwidget-val\" title=\"Brine "
        "in\" style=\"position:absolute;top:84px;left:8px;z-index:3;\">           <span class=\"hpwidget-name-spa"
        "n\" id=\"hpwidget-T_BRINE_IN\">"
        , 228);
    buf_str(out, state[2]);
    buf_add(out,
        "</span><span class=\"hpwidget-unit-span\">&deg;C</span></div> <div class=\"hpwidget-val\" title=\"Brine o"
        "ut\" style=\"position:absolute;top:210px;left:8px;z-index:3;\">          <span class=\"hpwidget-name-spa"
        "n\" id=\"hpwidget-T_BRINE_UT\">"
        , 228);
    buf_str(out, state[1]);
    buf_add(out, "</span><span class=\"hpwidget-unit-span\">&deg;C</span></div>  ", 61);
    if ((strcmp(state[18], "on") == 0)) {
        buf_add(out,
            "<div class=\"hpwidget-val\" title=\"HGW Temperature\" style=\"position:absolute;top:87px;left:76px;z-inde"
            "x:3;\"><span class=\"hpwidget-name-span\" id=\"hpwidget-HGW_VV\"></span>"
            , 167);
        buf_str(out, state[19]);
        buf_add(out, "<span class=\"hpwidget-unit-span\">&deg;C</span></div>", 52);
    }
    buf_add(out, " <div class=\"hpwidget-val\" title=\"Supply-line Temperature\" style=\"position:absolute;", 84);
    if ((v_dhw_on && (!v_demo))) {
        buf_add(out, "top:76px;left:98px", 18);
    } else {
        buf_add(out, "top:138px;left:131px", 20);
    }
    buf_add(out, ";z-index:3;\"><span class=\"hpwidget-name-span\" id=\"hpwidget-T_FRAM\"></span>", 74);
    buf_str(out, state[3]);
    buf_add(out,
        "<span class=\"hpwidget-unit-span\">&deg;C</span></div> <div class=\"hpwidget-val\" title=\"Supply pump\" s"
        "tyle=\"position:absolute;top:257px;left:146px;z-index:3;"
        , 155);
    if ((strcmp(state[20], "off") == 0)) {
        buf_add(out, "display:none;", 13);
    }
    buf_add(out, "\"><span class=\"hpwidget-name-span\" id=\"hpwidget-CIRK_SPEED\"></span>", 67);
    buf_str(out, state[21]);
    buf_add(out,
        "<span class=\"hpwidget-unit-span\">&nbsp;%</span></div> <div class=\"hpwidget-val\" title=\"Brine pump\" s"
        "tyle=\"position:absolute;top:156px;left:2px;z-index:3;"
        , 153);
    if ((strcmp(state[20], "off") == 0)) {
        buf_add(out, "display:none;", 13);
    }
    buf_add(out, "\"><span class=\"hpwidget-name-span\" id=\"hpwidget-BRINE_SPEED\"></span>", 68);
    buf_str(out, state[22]);
    buf_add(out,
        "<span class=\"hpwidget-unit-span\">&nbsp;%</span></div> <div class=\"hpwidget-val\" title=\"Return line T"
        "emperature\" style=\"position:absolute;top:205px;left:131px;z-index:3;\"><span class=\"hpwidget-name-spa"
        "n\" id=\"hpwidget-T_RETUR\"></span>"
        , 232);
    buf_str(out, state[4]);
    buf_add(out,
        "<span class=\"hpwidget-unit-span\">&deg;C</span></div> <div class=\"hpwidget-val\" title=\"Pressure pipe "
        "Temperature\" style=\"position:absolute;top:122px;left:73px;z-index:3;\"><span class=\"hpwidget-name-spa"
        "n\" id=\"hpwidget-TRYCKR_T\"></span>"
        , 233);
    buf_str(out, state[6]);
    buf_add(out,
        "<span class=\"hpwidget-unit-span\">&deg;C</span></div> <ha-icon icon=\"mdi:flash\" id=\"hpwidget-ELEFF\" s"
        "tyle=\"color:yellow;position:absolute;top:42px;left:82px;z-index:2;"
        , 166);
    if (((strcmp(state[23], "off") == 0) && (strcmp(state[24], "off") == 0))) {
        buf_add(out, "display:none", 12);
    }
    buf_add(out,
        "\"></ha-icon> <div id=\"hpwidget-KOMPR\" style=\"position:absolute;top:148px;left:66px;z-index:2;\"><styl"
        "e>.vppis .orbscr{transform:translate(1.5px,0);}.vppis-run .orbscr{animation:vpscrl 1.1s linear infin"
        "ite;}@keyframes vpscrl{0%{transform:translate(1.50px,0.00px)}8.3%{transform:translate(1.30px,0.75px)"
        "}16.7%{transform:translate(0.75px,1.30px)}25%{transform:translate(0.00px,1.50px)}33.3%{transform:tra"
        "nslate(-0.75px,1.30px)}41.7%{transform:translate(-1.30px,0.75px)}50%{transform:translate(-1.50px,0.0"
        "0px)}58.3%{transform:translate(-1.30px,-0.75px)}66.7%{transform:translate(-0.75px,-1.30px)}75%{trans"
        "form:translate(-0.00px,-1.50px)}83.3%{transform:translate(0.75px,-1.30px)}91.7%{transform:translate("
        "1.30px,-0.75px)}100%{transform:translate(1.50px,-0.00px)}}</style><svg width=\"44\" height=\"62\" viewBo"
        "x=\"0 0 40 58\" class=\"vppis"
        , 826);
    if ((v_demo || (strcmp(state[15], "on") == 0))) {
        buf_add(out, " vppis-run", 10);
    }
    buf_add(out,
        "\"><rect x=\"6.5\" y=\"1\" width=\"27\" height=\"56\" rx=\"13\" fill=\"#cfd8dc\" stroke=\"#455a64\" stroke-width=\"1"
        ".6\"/><line x1=\"20\" y1=\"28.5\" x2=\"20\" y2=\"34\" stroke=\"#607d8b\" stroke-width=\"2.5\"/><rect x=\"11\" y=\"34"
        "\" width=\"18\" height=\"15\" rx=\"2\" fill=\"#90a4ae\" stroke=\"#546e7a\" stroke-width=\"1\"/><line x1=\"13\" y1=\""
        "38\" x2=\"27\" y2=\"38\" stroke=\"#546e7a\" stroke-width=\"0.8\"/><line x1=\"13\" y1=\"41.5\" x2=\"27\" y2=\"41.5\" s"
        "troke=\"#546e7a\" stroke-width=\"0.8\"/><line x1=\"13\" y1=\"45\" x2=\"27\" y2=\"45\" stroke=\"#546e7a\" stroke-wi"
        "dth=\"0.8\"/><circle cx=\"20\" cy=\"16\" r=\"12.5\" fill=\"#eceff1\" stroke=\"#455a64\" stroke-width=\"1.6\"/><pat"
        "h d=\"M20.19 17.21L19.93 17.40L19.59 17.53L19.20 17.57L18.78 17.51L18.35 17.34L17.94 17.05L17.60 16.6"
        "4L17.33 16.14L17.19 15.55L17.17 14.91L17.31 14.25L17.60 13.60L18.05 13.00L18.65 12.49L19.38 12.11L20"
        ".22 11.89L21.11 11.85L22.03 12.01L22.93 12.38L23.76 12.95L24.47 13.72L25.03 14.65L25.38 15.72L25.50 "
        "16.87L25.36 18.06L24.97 19.23L24.32 20.32L23.42 21.27L22.32 22.04L21.04 22.57L19.64 22.82L18.19 22.7"
        "7L16.73 22.41L15.36 21.73L14.13 20.75L13.11 19.51L12.35 18.05L11.91 16.42L11.82 14.70L12.10 12.97L12"
        ".75 11.29L13.76 9.76L15.10 8.45L16.71 7.43L18.54 6.75\" fill=\"none\" stroke=\"#37474f\" stroke-width=\"1."
        "6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><g class=\"orbscr\"><defs><path id=\"scrorb\" d=\"M19."
        "81 14.79L20.07 14.60L20.41 14.47L20.80 14.43L21.22 14.49L21.65 14.66L22.06 14.95L22.40 15.36L22.67 1"
        "5.86L22.81 16.45L22.83 17.09L22.69 17.75L22.40 18.40L21.95 19.00L21.35 19.51L20.62 19.89L19.78 20.11"
        "L18.89 20.15L17.97 19.99L17.07 19.62L16.24 19.05L15.53 18.28L14.97 17.35L14.62 16.28L14.50 15.13L14."
        "64 13.94L15.03 12.77L15.68 11.68L16.58 10.73L17.68 9.96L18.96 9.43L20.36 9.18L21.81 9.23L23.27 9.59L"
        "24.64 10.27L25.87 11.25L26.89 12.49L27.65 13.95L28.09 15.58L28.18 17.30L27.90 19.03L27.25 20.71L26.2"
        "4 22.24L24.90 23.55L23.29 24.57L21.46 25.25\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"rou"
        "nd\"/></defs><use href=\"#scrorb\" stroke=\"#78909c\" stroke-width=\"2.6\"/><use href=\"#scrorb\" stroke=\"#37"
        "474f\" stroke-width=\"1\"/></g><circle cx=\"20\" cy=\"16\" r=\"1.4\" fill=\"#263238\"/></svg></div> <div id=\"hp"
        "widget-BRINESPIN\" style=\"position:absolute;top:124px;left:7px;z-index:2;\"><svg width=\"29\" height=\"29"
        "\" viewBox=\"0 0 26 26\"><circle cx=\"13\" cy=\"13\" r=\"11.5\" fill=\"var(--card-background-color,#ffffff)\" s"
        "troke=\"#37474f\" stroke-width=\"1.6\"/><circle cx=\"13\" cy=\"13\" r=\"11.5\" fill=\"#cfd8dc99\"/><g style=\"tra"
        "nsform-origin:0px 0px;transform:translate(13px,13px);"
        , 2453);
    if ((v_demo || (strcmp(state[14], "on") == 0))) {
        buf_add(out, "animation: vpimp 1.5s linear infinite;", 38);
    }
    buf_add(out,
        "\"><path d=\"M0 0 Q5.5 -1 7 -6\" fill=\"none\" stroke=\"#90a4ae\" stroke-width=\"4\" stroke-linecap=\"round\"/>"
        "<path d=\"M0 0 Q5.5 -1 7 -6\" fill=\"none\" stroke=\"#263238\" stroke-width=\"1.3\" stroke-linecap=\"round\"/>"
        "<path d=\"M0 0 Q5.5 -1 7 -6\" fill=\"none\" stroke=\"#90a4ae\" stroke-width=\"4\" stroke-linecap=\"round\" tra"
        "nsform=\"rotate(90)\"/><path d=\"M0 0 Q5.5 -1 7 -6\" fill=\"none\" stroke=\"#263238\" stroke-width=\"1.3\" str"
        "oke-linecap=\"round\" transform=\"rotate(90)\"/><path d=\"M0 0 Q5.5 -1 7 -6\" fill=\"none\" stroke=\"#90a4ae\""
        " stroke-width=\"4\" stroke-linecap=\"round\" transform=\"rotate(180)\"/><path d=\"M0 0 Q5.5 -1 7 -6\" fill=\""
        "none\" stroke=\"#263238\" stroke-width=\"1.3\" stroke-linecap=\"round\" transform=\"rotate(180)\"/><path d=\"M"
        "0 0 Q5.5 -1 7 -6\" fill=\"none\" stroke=\"#90a4ae\" stroke-width=\"4\" stroke-linecap=\"round\" transform=\"ro"
        "tate(270)\"/><path d=\"M0 0 Q5.5 -1 7 -6\" fill=\"none\" stroke=\"#263238\" stroke-width=\"1.3\" stroke-linec"
        "ap=\"round\" transform=\"rotate(270)\"/><circle cx=\"0\" cy=\"0\" r=\"2.6\" fill=\"#263238\"/></g></svg></div> <"
        "div id=\"hpwidget-CIRKPSPIN\" style=\"position:absolute;top:222px;left:144px;z-index:2;\"><svg width=\"29"
        "\" height=\"29\" viewBox=\"0 0 26 26\"><circle cx=\"13\" cy=\"13\" r=\"11.5\" fill=\"var(--card-background-color"
        ",#ffffff)\" stroke=\"#37474f\" stroke-width=\"1.6\"/><circle cx=\"13\" cy=\"13\" r=\"11.5\" fill=\"#cfd8dc99\"/><"
        "g style=\"transform-origin:0px 0px;transform:translate(13px,13px);"
        , 1365);
    if ((v_demo || (strcmp(state[10], "on") == 0))) {
        buf_add(out, "animation: vpimp 1.5s linear infinite;", 38);
    }
    buf_add(out,
        "\"><path d=\"M0 0 Q5.5 -1 7 -6\" fill=\"none\" stroke=\"#90a4ae\" stroke-width=\"4\" stroke-linecap=\"round\"/>"
        "<path d=\"M0 0 Q5.5 -1 7 -6\" fill=\"none\" stroke=\"#263238\" stroke-width=\"1.3\" stroke-linecap=\"round\"/>"
        "<path d=\"M0 0 Q5.5 -1 7 -6\" fill=\"none\" stroke=\"#90a4ae\" stroke-width=\"4\" stroke-linecap=\"round\" tra"
        "nsform=\"rotate(90)\"/><path d=\"M0 0 Q5.5 -1 7 -6\" fill=\"none\" stroke=\"#263238\" stroke-width=\"1.3\" str"
        "oke-linecap=\"round\" transform=\"rotate(90)\"/><path d=\"M0 0 Q5.5 -1 7 -6\" fill=\"none\" stroke=\"#90a4ae\""
        " stroke-width=\"4\" stroke-linecap=\"round\" transform=\"rotate(180)\"/><path d=\"M0 0 Q5.5 -1 7 -6\" fill=\""
        "none\" stroke=\"#263238\" stroke-width=\"1.3\" stroke-linecap=\"round\" transform=\"rotate(180)\"/><path d=\"M"
        "0 0 Q5.5 -1 7 -6\" fill=\"none\" stroke=\"#90a4ae\" stroke-width=\"4\" stroke-linecap=\"round\" transform=\"ro"
        "tate(270)\"/><path d=\"M0 0 Q5.5 -1 7 -6\" fill=\"none\" stroke=\"#263238\" stroke-width=\"1.3\" stroke-linec"
        "ap=\"round\" transform=\"rotate(270)\"/><circle cx=\"0\" cy=\"0\" r=\"2.6\" fill=\"#263238\"/></g></svg></div> <"
        "ha-icon icon=\"mdi:alert-circle\" id=\"hpwidget-ALERT\" style=\"color:red;position:absolute;top:42px;left"
        ":82px;z-index:4;animation: blink  1s steps(5, start) infinite;"
        , 1162);
    if ((strcmp(state[25], "Ok") == 0)) {
        buf_add(out, "display:none", 12);
    }
    buf_add(out,
        "\"></ha-icon> <ha-icon icon=\"mdi:stop\" id=\"hpwidget-EVU\" style=\"color:red;position:absolute;top:62px;"
        "left:82px;z-index:3;animation: blink  1s steps(5, start) infinite;"
        , 166);
    if ((strcmp(state[26], "on") == 0)) {
        buf_add(out, " ", 1);
    } else {
        buf_add(out, "display:none", 12);
    }
    buf_add(out,
        "\">EVU</ha-icon> </div> <div class=\"hpwidget-vald\" title=\"Indoor Temperature\" style=\"position:absolut"
        "e;top:64px;left: 221px;z-index:2;\"><span class=\"hpwidget-name-span\" id=\"hpwidget-INDR_T\"></span>"
        , 196);
    buf_str(out, state[27]);
    buf_add(out,
        "<span class=\"hpwidget-unit-spand\">&deg;C</span></div> <div class=\"hpwidget-vald\" title=\"Outdoor Temp"
        "erature\" style=\"position:absolute;top:14px;left:221px;z-index:2;\"><span class=\"hpwidget-name-span\" i"
        "d=\"hpwidget-OUTDOOR_T\"></span>"
        , 230);
    buf_str(out, state[11]);
    buf_add(out,
        "<span class=\"hpwidget-unit-spand\">&deg;C</span></div> <ha-icon icon=\"mdi:home-roof\"id=\"hpwidget-roof"
        "\" style=\"color:grey;position:absolute;top:26px;left:205px;z-index:4;--mdc-icon-size:65px;\">Temp</ha-"
        "icon>\012      \012</div>"
        , 219);
}
